### PR TITLE
Issue33 - meta.py - set all size to 0 or if required, remove a few size:0

### PR DESCRIPTION
**Pull request by maggienj**
Few set to 0. Wherever size must be greater than 0 err raised, those were removed.
Ran all unit-tests. It appears there are no more "size must be greater than 0" errs. 
So, sending this pull request.
Not sure, if any other particular unit test should be tested as it appears to be common for all unit tests.

### CODE REVIEW

**Comment by klahnakoski** [comment]
you missed at least 5 instances of size=1.  This includes *.js files.

**Comment by maggienj** [comment]
Didn't realize other files would have been part of this issue....  thought this was just for meta.py.
Will look for *.js files too...

**Comment by maggienj** [comment]
size:1 changed to size:0 in few instances in *.js .

**Comment by maggienj** [comment]
one more instance changed from size:1 to size:0 in *.js

**Comment by klahnakoski** [comment]
util.py still has two `"size": 1`

**Comment by klahnakoski** [comment]
there is also `"size": 100 if DEBUG else 1` which should change `1` to `None`

**Comment by maggienj** [comment]
the DEBUG line was changed in one instance earlier. Will check for other instances too..

**Comment by maggienj** [comment]
*had the file mask to *.js and missed this util.py and  for some reason i had been thinking it has to be changed only to meta.py and then to *.js and  that is why missed these instances.

**Comment by maggienj** [comment]
now, doing a full search for "size" to see if any is set to 1... i mean in DEBUG line or in query property.

**Comment by maggienj** [comment]
es09/setop.py has one instance too.  Some part of es09 is still in use, in this version.
 *Up until, this(es09) is duplicated for ES5, will update this es09/setop.py too.

**Pull request merged**
